Repository Kek-i/KEKI_Android, pull requests merged in 2023-03, with the labels that each got.

#157 Feature/144 like server
  README.md
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddActivity.kt
  app/src/main/res/layout/fragment_consumer_like.xml
Labels: chore

#158 Feature/133 seller product detail feed
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/auth/SignoutRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerProductFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/SellerProductDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/SellerProductFeedDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/SellerProductFeedDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/SellerProductAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/SellerProductAddRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/SellerProductAddService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/SellerProductAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/SellerProductEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/model/SellerProductAddBody.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/product/model/SellerProductAddResponse.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerProductDetailFeedDeleteDialog.kt
Labels: feature🔨

#159 Feature/137 seller add feed server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/SellerStoreFeedAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/SellerStoreFeedAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/SellerStoreFeedAddRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/SellerStoreFeedAddService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/SellerStoreFeedAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/model/DessertName.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/model/PostStoreFeedRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/model/ResultFeedAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/model/SellerFeedAddViewResponse.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeedadd/ProductNameAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeedadd/ProductNameData.kt
  app/src/main/res/layout/activity_seller_store_feed_add.xml
  app/src/main/res/layout/item_feed_image_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#160 Feature/113 seller store feed server
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerProductFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainStoreAdapter.kt
Labels: feature🔨

#163 Feat/ 122 Reissue Token
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/config/ReissueRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/codepatissier/keki/config/model/PostReissueRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginActivity.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/LogoutDialog.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
Labels: feature🔨

#166 Chore/164 modification list
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/ConsumerCalendarAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/RecentSeenFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/model/RecentSeenFeedResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/ConsumerSearchActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreMainFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storeadd/SellerStoreFeedAddActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchPopularAdapter.kt
  app/src/main/res/drawable/bg_oval_light_yellow.xml
  app/src/main/res/drawable/bg_rectangle_radius_10_white_2_no_padding.xml
  app/src/main/res/drawable/bg_rectangle_radius_13_light_peach_2.xml
  app/src/main/res/drawable/bg_rectangle_radius_16_light_yellow.xml
  app/src/main/res/drawable/oval_light_yellow.xml
  app/src/main/res/layout/activity_consumer_search.xml
  app/src/main/res/layout/activity_consumer_store_main.xml
  app/src/main/res/layout/activity_seller_product_add_and_edit.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/layout/fragment_seller_store_main.xml
  app/src/main/res/layout/item_search_list_recycler.xml
  app/src/main/res/layout/search_custom_spinner.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#168 fix: seller 피드 삭제 후 화면 이동 수정
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storedetail/SellerStoreFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storedetail/delete/SellerStoreDetailFeedDeleteDialog.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/SellerStoreFeedAdapter.kt
Labels: fix

#170 chore: data class 수정
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/model/Image.kt
Labels: bug, chore

#174 feat: 이미지 연결 코드 수정
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/StoreFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/model/Feed.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/SellerStoreFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/productdetail/SellerFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storedetail/SellerStoreFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/storedetail/SellerStoreFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/home/HomeStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/like/LikeFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchListAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchRecentPostAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchResultFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/SellerStoreFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedData.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainStoreAdapter.kt
  app/src/main/res/layout/activity_consumer_one_feed_detail.xml
  app/src/main/res/layout/activity_consumer_store_main.xml
Labels: chore
