Repository Kek-i/KEKI_Android, pull requests merged in 2023-01, with the labels that each got.

#2 Feature/1 setting
  .gitignore
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/MainActivity.kt
  app/src/main/java/com/umc/keki/config/ApplicationClass.kt
  app/src/main/java/com/umc/keki/config/BaseActivity.kt
  app/src/main/java/com/umc/keki/config/BaseFragment.kt
  app/src/main/java/com/umc/keki/config/BaseResponse.kt
  app/src/main/java/com/umc/keki/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/umc/keki/src/MainActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/home/ConsumerHomeFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/like/ConsumerLikeFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/umc/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/umc/keki/util/LoadingDialog.kt
  app/src/main/res/drawable-v24/ic_calendar.png
  app/src/main/res/drawable-v24/ic_home.png
  app/src/main/res/drawable-v24/ic_like.png
  app/src/main/res/drawable-v24/ic_mypage.png
  app/src/main/res/drawable-v24/ic_search.png
  app/src/main/res/drawable-v24/main_btm_nav_item_color.xml
  app/src/main/res/drawable-v24/softsquared_logo.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_consumer_calendar.xml
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/fragment_consumer_like.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/menu/menu_consumer_main_bottom_nav.xml
  app/src/main/res/menu/menu_seller_main_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/network_security_config.xml
  settings.gradle
Labels: feature

#5 feat:스플래시 화면 생성
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable-hdpi/keki_korean_logo.png
  app/src/main/res/drawable-mdpi/keki_korean_logo.png
  app/src/main/res/drawable-v24/splash_comment.png
  app/src/main/res/drawable-xhdpi/keki_korean_logo.png
  app/src/main/res/drawable-xxhdpi/keki_korean_logo.png
  app/src/main/res/drawable-xxxhdpi/keki_korean_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#11 Feature/8 search main
  .idea/misc.xml
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchCakeImgAdapter.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchCakeImgData.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchPopularAdapter.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchPopularData.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchRecentAdapter.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchRecentData.kt
  app/src/main/res/drawable-hdpi/ic_search.png
  app/src/main/res/drawable-mdpi/ic_search.png
  app/src/main/res/drawable-v24/ic_search.png
  app/src/main/res/drawable-v24/img_cake.jpg
  app/src/main/res/drawable-xhdpi/ic_search.png
  app/src/main/res/drawable-xxhdpi/ic_search.png
  app/src/main/res/drawable-xxxhdpi/ic_search.png
  app/src/main/res/drawable/bg_rectangle_radius_13_grey_border.xml
  app/src/main/res/drawable/bg_rectangle_radius_13_light_peach_1.xml
  app/src/main/res/drawable/bg_rectangle_radius_13_very_light_pink.xml
  app/src/main/res/drawable/bg_rectangle_radius_23_very_light_pink.xml
  app/src/main/res/drawable/bg_underline_brown_grey.xml
  app/src/main/res/drawable/drawable_search_ic_resize.xml
  app/src/main/res/drawable/search_cv_shadow.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/layout/item_recent_seen_cake_recycler.xml
  app/src/main/res/layout/item_search_popular_recycler.xml
  app/src/main/res/layout/item_search_recent_recycler.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#13 chore: splash UI 수정
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#15 chore: color, string 추가
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#16 Feature/12 search detail
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchCakeImgAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchCakeImgData.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchListAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchListData.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchPopularAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchPopularData.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchRecentAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/search/SearchRecentData.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchCakeImgData.kt
  app/src/main/java/com/umc/keki/util/recyler/search/SearchPopularData.kt
  app/src/main/res/drawable-hdpi/ic_cake_off.png
  app/src/main/res/drawable-hdpi/ic_chevron_down.png
  app/src/main/res/drawable-hdpi/ic_delete_search.png
  app/src/main/res/drawable-mdpi/ic_cake_off.png
  app/src/main/res/drawable-mdpi/ic_chevron_down.png
  app/src/main/res/drawable-mdpi/ic_delete_search.png
  app/src/main/res/drawable-xhdpi/ic_cake_off.png
  app/src/main/res/drawable-xhdpi/ic_chevron_down.png
  app/src/main/res/drawable-xhdpi/ic_delete_search.png
  app/src/main/res/drawable-xxhdpi/ic_cake_off.png
  app/src/main/res/drawable-xxhdpi/ic_chevron_down.png
  app/src/main/res/drawable-xxhdpi/ic_delete_search.png
  app/src/main/res/drawable-xxxhdpi/ic_cake_off.png
  app/src/main/res/drawable-xxxhdpi/ic_chevron_down.png
  app/src/main/res/drawable-xxxhdpi/ic_delete_search.png
  app/src/main/res/drawable/bg_spinner_box.xml
  app/src/main/res/drawable/drawable_delete_ic_resize.xml
  app/src/main/res/layout/activity_consumer_search.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/layout/item_search_list_recycler.xml
  app/src/main/res/layout/search_custom_spinner.xml
  app/src/main/res/layout/search_custom_spinner_list.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/spinner_array.xml
  app/src/main/res/values/strings.xml
Labels: feature

#18 Feature/7 storemain UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/store/ProductFeedFragment.kt
  app/src/main/java/com/umc/keki/src/store/SellerFeedFragment.kt
  app/src/main/java/com/umc/keki/src/store/StoreMainActivity.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainAdapter.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainData.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainDialog.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainVPAdapter.kt
  app/src/main/res/drawable-hdpi/ic_chevron_left.png
  app/src/main/res/drawable-hdpi/ic_info.png
  app/src/main/res/drawable-hdpi/ic_store_main_cake.png
  app/src/main/res/drawable-hdpi/ic_store_main_grid.png
  app/src/main/res/drawable-hdpi/ic_store_main_plus.png
  app/src/main/res/drawable-hdpi/img_store_main_dialog.png
  app/src/main/res/drawable-hdpi/img_store_main_dialog_arm.png
  app/src/main/res/drawable-mdpi/ic_chevron_left.png
  app/src/main/res/drawable-mdpi/ic_info.png
  app/src/main/res/drawable-mdpi/ic_store_main_cake.png
  app/src/main/res/drawable-mdpi/ic_store_main_grid.png
  app/src/main/res/drawable-mdpi/ic_store_main_plus.png
  app/src/main/res/drawable-mdpi/img_store_main_dialog.png
  app/src/main/res/drawable-mdpi/img_store_main_dialog_arm.png
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_light_pink.xml
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_off_white.xml
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_white.xml
  app/src/main/res/drawable-xhdpi/ic_chevron_left.png
  app/src/main/res/drawable-xhdpi/ic_info.png
  app/src/main/res/drawable-xhdpi/ic_store_main_cake.png
  app/src/main/res/drawable-xhdpi/ic_store_main_grid.png
  app/src/main/res/drawable-xhdpi/ic_store_main_plus.png
  app/src/main/res/drawable-xhdpi/img_store_main_dialog.png
  app/src/main/res/drawable-xhdpi/img_store_main_dialog_arm.png
  app/src/main/res/drawable-xxhdpi/ic_chevron_left.png
  app/src/main/res/drawable-xxhdpi/ic_info.png
  app/src/main/res/drawable-xxhdpi/ic_store_main_cake.png
  app/src/main/res/drawable-xxhdpi/ic_store_main_grid.png
  app/src/main/res/drawable-xxhdpi/ic_store_main_plus.png
  app/src/main/res/drawable-xxhdpi/img_store_main_dialog.png
  app/src/main/res/drawable-xxhdpi/img_store_main_dialog_arm.png
  app/src/main/res/drawable-xxxhdpi/ic_chevron_left.png
  app/src/main/res/drawable-xxxhdpi/ic_info.png
  app/src/main/res/drawable-xxxhdpi/ic_store_main_cake.png
  app/src/main/res/drawable-xxxhdpi/ic_store_main_grid.png
  app/src/main/res/drawable-xxxhdpi/ic_store_main_plus.png
  app/src/main/res/drawable-xxxhdpi/img_store_main_dialog.png
  app/src/main/res/drawable-xxxhdpi/img_store_main_dialog_arm.png
  app/src/main/res/drawable/bg_rectangle_oval_light_yellow.xml
  app/src/main/res/drawable/tab_select_underline.xml
  app/src/main/res/layout/activity_store_main.xml
  app/src/main/res/layout/dialog_store_main.xml
  app/src/main/res/layout/fragment_product_feed.xml
  app/src/main/res/layout/fragment_seller_feed.xml
  app/src/main/res/layout/item_store_main_recycler.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#22 Feature/6 calendarmain UI
  app/build.gradle
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/umc/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
  app/src/main/res/drawable-hdpi/bg_calendar_item_del.png
  app/src/main/res/drawable-mdpi/bg_calendar_item_del.png
  app/src/main/res/drawable-xhdpi/bg_calendar_item_del.png
  app/src/main/res/drawable-xxhdpi/bg_calendar_item_del.png
  app/src/main/res/drawable-xxxhdpi/bg_calendar_item_del.png
  app/src/main/res/layout/fragment_consumer_calendar.xml
  app/src/main/res/layout/item_calendar_anniversary_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#24 Feature/10 store feed
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/main/consumer/store/ConsumerStoreFeedActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/store/DetailImageAdapter.kt
  app/src/main/java/com/umc/keki/src/main/consumer/store/StoreFeedSlideImageFragment.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedData.kt
  app/src/main/res/drawable-hdpi/ic_bottom_heart_off.png
  app/src/main/res/drawable-hdpi/ic_bottom_heart_on.png
  app/src/main/res/drawable-hdpi/ic_report.png
  app/src/main/res/drawable-mdpi/ic_bottom_heart_off.png
  app/src/main/res/drawable-mdpi/ic_bottom_heart_on.png
  app/src/main/res/drawable-mdpi/ic_report.png
  app/src/main/res/drawable-v24/bg_rectangle_radius_16_light_peach.xml
  app/src/main/res/drawable-xhdpi/ic_bottom_heart_off.png
  app/src/main/res/drawable-xhdpi/ic_bottom_heart_on.png
  app/src/main/res/drawable-xhdpi/ic_report.png
  app/src/main/res/drawable-xxhdpi/ic_bottom_heart_off.png
  app/src/main/res/drawable-xxhdpi/ic_bottom_heart_on.png
  app/src/main/res/drawable-xxhdpi/ic_report.png
  app/src/main/res/drawable-xxxhdpi/ic_bottom_heart_off.png
  app/src/main/res/drawable-xxxhdpi/ic_bottom_heart_on.png
  app/src/main/res/drawable-xxxhdpi/ic_report.png
  app/src/main/res/drawable/oval_light_yellow.xml
  app/src/main/res/drawable/rec_radius_10_white.xml
  app/src/main/res/layout/activity_consumer_store_feed.xml
  app/src/main/res/layout/fragment_store_feed_slide_image.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#26 chore : 스토어 메인 판매자, 상품 리싸이클러뷰 어댑터 나누기
  app/src/main/java/com/umc/keki/src/store/ProductFeedFragment.kt
  app/src/main/java/com/umc/keki/src/store/SellerFeedFragment.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainProductAdapter.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainSellerAdapter.kt
Labels: feature🔨

#25 Feature/20 mypage customer UI
  app/src/main/java/com/umc/keki/src/MainActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerConditionFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerProfileEditFragment.kt
  app/src/main/res/drawable-hdpi/ic_camera.png
  app/src/main/res/drawable-hdpi/img_my_page_terms_condition.png
  app/src/main/res/drawable-mdpi/ic_camera.png
  app/src/main/res/drawable-mdpi/img_my_page_terms_condition.png
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_white_not_padding.xml
  app/src/main/res/drawable-xhdpi/ic_camera.png
  app/src/main/res/drawable-xhdpi/img_my_page_terms_condition.png
  app/src/main/res/drawable-xxhdpi/ic_camera.png
  app/src/main/res/drawable-xxhdpi/img_my_page_terms_condition.png
  app/src/main/res/drawable-xxxhdpi/ic_camera.png
  app/src/main/res/drawable-xxxhdpi/img_my_page_terms_condition.png
  app/src/main/res/drawable/bg_oval_off_white.xml
  app/src/main/res/drawable/bg_oval_pale_salmon.xml
  app/src/main/res/drawable/switch_thumb_push_notification.xml
  app/src/main/res/drawable/switch_track_push_notification.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_consumer_condition.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_consumer_profile_edit.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#29 chore: 함수로 정리
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchFragment.kt
Labels: feature🔨

#30 Feature/21 calendar detail UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarDetailActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/umc/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/calendar/CalendarAnniversaryData.kt
  app/src/main/res/drawable-hdpi/ic_calendar_detail_modify.png
  app/src/main/res/drawable-hdpi/ic_chevron_right_darkish_pink.png
  app/src/main/res/drawable-hdpi/img_calendar_detail_cake.png
  app/src/main/res/drawable-mdpi/ic_calendar_detail_modify.png
  app/src/main/res/drawable-mdpi/ic_chevron_right_darkish_pink.png
  app/src/main/res/drawable-mdpi/img_calendar_detail_cake.png
  app/src/main/res/drawable-xhdpi/ic_calendar_detail_modify.png
  app/src/main/res/drawable-xhdpi/ic_chevron_right_darkish_pink.png
  app/src/main/res/drawable-xhdpi/img_calendar_detail_cake.png
  app/src/main/res/drawable-xxhdpi/ic_calendar_detail_modify.png
  app/src/main/res/drawable-xxhdpi/ic_chevron_right_darkish_pink.png
  app/src/main/res/drawable-xxhdpi/img_calendar_detail_cake.png
  app/src/main/res/drawable-xxxhdpi/ic_calendar_detail_modify.png
  app/src/main/res/drawable-xxxhdpi/ic_chevron_right_darkish_pink.png
  app/src/main/res/drawable-xxxhdpi/img_calendar_detail_cake.png
  app/src/main/res/drawable/bg_rectangle_radius_10_light_pink.xml
  app/src/main/res/drawable/bg_rectangle_radius_10_white.xml
  app/src/main/res/drawable/bg_rectangle_radius_13_light_peach_2.xml
  app/src/main/res/drawable/bg_rectangle_radius_13_off_white.xml
  app/src/main/res/layout/activity_consumer_calendar_detail.xml
  app/src/main/res/layout/fragment_consumer_calendar.xml
  app/src/main/res/layout/item_calendar_anniversary_recycler.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#35 Feature/31 calendar add UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarAddActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/res/drawable-hdpi/ic_calendar_select_date.png
  app/src/main/res/drawable-hdpi/ic_down_arrow.png
  app/src/main/res/drawable-mdpi/ic_calendar_select_date.png
  app/src/main/res/drawable-mdpi/ic_down_arrow.png
  app/src/main/res/drawable-xhdpi/ic_calendar_select_date.png
  app/src/main/res/drawable-xhdpi/ic_down_arrow.png
  app/src/main/res/drawable-xxhdpi/ic_calendar_select_date.png
  app/src/main/res/drawable-xxhdpi/ic_down_arrow.png
  app/src/main/res/drawable-xxxhdpi/ic_calendar_select_date.png
  app/src/main/res/drawable-xxxhdpi/ic_down_arrow.png
  app/src/main/res/drawable/bg_rectangle_radius_13_white.xml
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: feature🔨

#34 FEATURE/ 28 store product detail feed UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/main/consumer/search/ConsumerSearchActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/store/productfeed/ConsumerStoreProductFeedActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/store/productfeed/StoreProductFeedData.kt
  app/src/main/java/com/umc/keki/src/main/consumer/store/productfeed/StoreProductFeedSlideImageFragment.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/layout/activity_store_product_feed.xml
  app/src/main/res/layout/fragment_store_product_feed_slide_image.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/values/dimens.xml
Labels: feature🔨

#36 Feature/20 mypage customer UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/MainActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerConditionActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerConditionFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerProfileEditActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/ConsumerProfileEditFragment.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/NoticeActivity.kt
  app/src/main/java/com/umc/keki/src/main/consumer/mypage/NoticeDetailActivity.kt
  app/src/main/java/com/umc/keki/src/storeMain/ProductFeedFragment.kt
  app/src/main/java/com/umc/keki/src/storeMain/SellerFeedFragment.kt
  app/src/main/java/com/umc/keki/src/storeMain/StoreMainActivity.kt
  app/src/main/java/com/umc/keki/util/recycler/home/HomeStoreAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/notice/NoticeAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/notice/NoticeData.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainData.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainVPAdapter.kt
  app/src/main/res/layout/activity_consumer_condition.xml
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/activity_store_main.xml
  app/src/main/res/layout/fragment_consumer_condition.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_consumer_profile_edit.xml
  app/src/main/res/layout/fragment_product_feed.xml
  app/src/main/res/layout/fragment_seller_feed.xml
  app/src/main/res/layout/item_notice_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨, chore

#37 Feature/31 calendar add UI
  app/src/main/java/com/umc/keki/src/main/consumer/calendar/ConsumerCalendarAddActivity.kt
  app/src/main/java/com/umc/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_light_pink_padding.xml
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_white_not_padding.xml
  app/src/main/res/drawable-v24/bg_rectangle_radius_10_white_padding.xml
  app/src/main/res/drawable/bg_rectangle_radius_10_light_pink_no_padding.xml
  app/src/main/res/drawable/bg_rectangle_radius_10_white_no_padding.xml
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/layout/activity_consumer_calendar_detail.xml
  app/src/main/res/layout/activity_store_main.xml
  app/src/main/res/layout/dialog_access_right.xml
  app/src/main/res/layout/dialog_store_main.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/values/colors.xml
Labels: chore

#38 chore: 접근권한 팝업 UI 조정
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/umc/keki/util/viewpager/login/AccessRightDialog.kt
  app/src/main/res/layout/dialog_access_right.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#41 Feature/33 chore login UI
  app/src/main/java/com/umc/keki/util/viewpager/login/AccessRightDialog.kt
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_access_right.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#42 Feature/33 chore login UI
  app/src/main/java/com/umc/keki/src/main/login/EditProfileActivity.kt
  app/src/main/java/com/umc/keki/src/main/login/IntroActivity.kt
  app/src/main/java/com/umc/keki/src/main/login/LoginActivity.kt
  app/src/main/res/layout/activity_intro.xml
Labels: chore

#44 Feature/40 chore home UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/keki/src/storeMain/ProductFeedFragment.kt
  app/src/main/java/com/umc/keki/src/storeMain/SellerFeedFragment.kt
  app/src/main/java/com/umc/keki/src/storeMain/StoreMainActivity.kt
  app/src/main/java/com/umc/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/umc/keki/util/viewpager/storemain/StoreMainVPAdapter.kt
  app/src/main/res/layout/activity_consumer_store_detail_feed.xml
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/item_home_store_recycler.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/values/dimens.xml
Labels: feature🔨, chore

#46 Feature/31 기념일 추가 화면 해시태그 정렬
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarAddActivity.kt
  app/src/main/res/layout/activity_consumer_calendar_add.xml
Labels: feature🔨

#47 Chore/33 chore login UI
  app/src/main/java/com/codepatissier/keki/src/main/login/EditProfileActivity.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/login/AccessRightDialog.kt
  app/src/main/res/drawable/bg_rectangle_radius_10_shadow.xml
  app/src/main/res/layout/activity_consumer_profile_setting.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#48 Feature/10 store feed
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedDialog.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/drawable-hdpi/ic_check.png
  app/src/main/res/drawable-hdpi/ic_none_check.png
  app/src/main/res/drawable-mdpi/ic_check.png
  app/src/main/res/drawable-mdpi/ic_none_check.png
  app/src/main/res/drawable-xhdpi/ic_check.png
  app/src/main/res/drawable-xhdpi/ic_none_check.png
  app/src/main/res/drawable-xxhdpi/ic_check.png
  app/src/main/res/drawable-xxhdpi/ic_none_check.png
  app/src/main/res/drawable-xxxhdpi/ic_check.png
  app/src/main/res/drawable-xxxhdpi/ic_none_check.png
  app/src/main/res/layout/activity_consumer_store_detail_feed.xml
  app/src/main/res/layout/dialog_report_consumer_store_detail_feed.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/menu/popup_menu_report_consumer_store_detail_feed.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨, chore

#51 Feature/49 app design
  app/src/main/res/drawable-v24/main_btm_nav_item_color.xml
  app/src/main/res/layout/activity_consumer_condition.xml
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/activity_consumer_store_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/fragment_consumer_like.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_consumer_product_feed.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/layout/fragment_consumer_store_feed.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature🔨

#52 Feature/6 캘린더 메인 화면 상세 기능 모두 구현
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/calendar/CalendarAnniversaryData.kt
  app/src/main/res/layout/item_calendar_anniversary_recycler.xml
Labels: feature🔨

#55 Feature/54 popular search
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/SearchRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/SearchService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/SearchView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/model/PopularSearchesResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/model/Result.kt
  app/src/main/res/xml/network_security_config.xml
Labels: feature🔨

#61 Feature/58 cs notice server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/NoticeActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/NoticeDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/ConsumerNoticeRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/ConsumerNoticeService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/ConsumerNoticeView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/NoticeActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/model/ConsumerNoticeResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/ConsumerNoticeDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/ConsumerNoticeDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/ConsumerNoticeDetailView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/NoticeDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/model/ConsumerNoticeDetailResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/noticedetail/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/notice/NoticeAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/notice/NoticeData.kt
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/item_notice_recycler.xml
  app/src/main/res/values/dimens.xml
Labels: feature🔨, chore

#60 Feature/31 calendar add UI
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarAddActivity.kt
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: feature🔨, chore

#62 Feature/57 store main profile server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/info/ConsumerStoreInfoRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/info/ConsumerStoreInfoService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/info/ConsumerStoreInfoView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/info/model/ConsumerStoreInfoResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/info/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/model/ConsumerStoreMainResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/model/Result.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/StoreMainDialog.kt
  app/src/main/res/layout/activity_consumer_store_main.xml
  app/src/main/res/layout/dialog_store_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#64 Feature/59 calendar main server - 기념일 전체/상세 조회 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/ConsumerCalendarDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/ConsumerCalendarDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/ConsumerCalendarDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/ConsumerCalendarDetailView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/model/ConsumerCalendarDetailResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/model/ResultCalendarDetail.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/model/ConsumerCalendarListResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/model/ResultCalendar.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/calendar/CalendarAnniversaryData.kt
Labels: feature🔨

#68 feat : 서버 주문 링크 추가
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/model/Result.kt
  app/src/main/res/layout/activity_consumer_store_main.xml
Labels: feature🔨

#72 Feature/67 calendar add server
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/ConsumerCalendarAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/ConsumerCalendarAddRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/ConsumerCalendarAddService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/ConsumerCalendarAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/model/ConsumerCalendarTagListResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/model/PostCalendarRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendaradd/model/ResultCalendarTag.kt
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/layout/activity_consumer_calendar_detail.xml
  app/src/main/res/layout/fragment_consumer_calendar.xml
  app/src/main/res/layout/single_chip_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: feature🔨

#78 feat: 기념일 delete patch api 서버 연결
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/ConsumerCalendarView.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/calendar/CalendarAnniversaryAdapter.kt
Labels: feature🔨

#79 chore: 버튼색 사라짐 문제로 인한 AppTheme 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/styles.xml
Labels: chore

#80 캘린더 추가/상세 화면 버튼 크기 확대 및 간격 조정
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/layout/activity_consumer_calendar_detail.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#84 Feature/76 mypage dialog UI
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/LogoutDialog.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
  app/src/main/res/drawable/bg_rectangle_radius_10_white_2_no_padding.xml
  app/src/main/res/drawable/bg_rectangle_radius_20_white_no_padding.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_withdrawal.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#81 Feature/74 mypage profile edit server
  app/build.gradle
  app/src/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/model/ConsumerMyPageResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/model/MyPageResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/NoticeActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/model/ConsumerNoticeResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/notice/model/NoticeResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/model/ConsumerProfileEditBody.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/model/ConsumerProfileEditResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/model/ConsumerStoreMainResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/model/StoreMainResult.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature🔨

#83 Feature/77 consumer store product detail feed server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/ConsumerStoreProductDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/StoreProductFeedData.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductFeedDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductFeedDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductFeedDetailView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/StoreProductFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/model/ConsumerStoreProductFeedDetailResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/model/Image.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/model/ProductFeedDetailResult.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/StoreMainProductAdapter.kt
  app/src/main/res/layout/fragment_store_product_feed_slide_image.xml
Labels: feature🔨

#82 Feature/45 search server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/SearchMainService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/SearchMainView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/ConsumerSearchActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultService.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchPopularAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchRecentAdapter.kt
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/values/styles.xml
Labels: feature🔨

#75 Feature/65 login server
  app/build.gradle
  app/client_secret_183252467381-nvrjh0voev6f9kmhmus97ccek0hracb4.apps.googleusercontent.com.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/MainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/NonConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/EditProfileActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/IntroActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/LoginActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/LoginRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/LoginService.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/LoginView.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/PostLoginRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/PostSignupRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/SocialLoginResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/SocialTokenResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/SignupRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/SignupService.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/SignupView.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/model/PostNickRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/model/PostNickname.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/res/layout/activity_consumer_profile_setting.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: feature🔨

#85 Feature/56 store detail feed server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedDialog.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreFeedDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreFeedDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreFeedDetailView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/DetailImageAdapter.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/StoreFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/model/ConsumerStoreDetailFeedResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/model/Feed.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/report/ConsumerStoreDetailFeedDialog.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedData.kt
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/item_progressbar_loading.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
Labels: feature🔨, chore

#89 Feature/87 logout server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/MainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/IntroActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginService.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginView.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LogoutRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LogoutService.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LogoutView.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/SignoutRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/SignoutService.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/SignoutView.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/model/PostLoginRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/model/PostSignupRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/model/SocialTokenResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/SignupRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/SignupService.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/SignupView.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/model/PostNickRequest.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/model/PostNickname.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/NonConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/model/SocialLoginResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/SignupRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/login/profilesetting/model/PostNickRequest.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/LogoutDialog.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/login/AccessRightDialog.kt
Labels: feature🔨

#91 Feature/74 mypage profile edit server
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
Labels: chore

#92 Feature/63 store main feed server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/fragment_non_consumer_calendar.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: chore

#94 Feature/65 login server
  app/build.gradle
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/LoginActivity.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/LogoutDialog.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
  app/src/main/res/values/strings.xml
Labels: feature🔨

#96 Feature/45 search server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/ConsumerSearchActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultService.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchRecentPostAdapter.kt
  app/src/main/res/values/spinner_array.xml
Labels: feature🔨

#99 Chore/88 modify UI
  app/src/main/java/com/codepatissier/keki/src/MainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/NonConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/StoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/StoreMainStoreAdapter.kt
  app/src/main/res/layout/activity_consumer_calendar_detail.xml
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/activity_consumer_profile_setting.xml
  app/src/main/res/layout/fragment_consumer_my_page.xml
  app/src/main/res/layout/fragment_consumer_store_feed.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/layout/item_store_main_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: chore

#97 Feature/93 store feed report server
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/ConsumerHomeFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/report/ConsumerStoreDetailFeedDialog.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/report/ConsumerStoreDetailFeedReportRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/report/ConsumerStoreDetailFeedReportService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/report/ConsumerStoreDetailFeedReportView.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/home/HomeStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/layout/dialog_report_consumer_store_detail_feed.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨, chore

#100 chore: 스토어 상품 상세 피드 연결 수정
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerProductFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/productfeed/productdetail/ConsumerStoreProductDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/StoreMainProductAdapter.kt
Labels: chore
