Repository Kek-i/KEKI_Android, pull requests merged in 2023-02, with the labels that each got.

#101 Chore/88 modify UI
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/res/layout/activity_consumer_profile_setting.xml
  app/src/main/res/values/dimens.xml
Labels: chore, fix

#105 feat: 판매자 프로필 설정 화면
  app/src/main/res/layout/activity_seller_profile_edit.xml
  app/src/main/res/layout/activity_seller_profile_setting.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#109 Feature/50 seller profile setting UI
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/CustomerProfileSettingActivity.kt
  app/src/main/res/values/dimens.xml
Labels: chore

#108 Feature/102 UI home feed detail
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/ConsumerHomeFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
Labels: chore

#116 Feature/103 seller add feed UI
  app/build.gradle
  app/src/main/res/drawable-hdpi/ic_add.png
  app/src/main/res/drawable-hdpi/ic_img_delete.png
  app/src/main/res/drawable-mdpi/ic_add.png
  app/src/main/res/drawable-mdpi/ic_img_delete.png
  app/src/main/res/drawable-xhdpi/ic_add.png
  app/src/main/res/drawable-xhdpi/ic_img_delete.png
  app/src/main/res/drawable-xxhdpi/ic_add.png
  app/src/main/res/drawable-xxhdpi/ic_img_delete.png
  app/src/main/res/drawable-xxxhdpi/ic_add.png
  app/src/main/res/drawable-xxxhdpi/ic_img_delete.png
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/layout/activity_seller_store_feed_add.xml
  app/src/main/res/layout/item_feed_image_recycler.xml
  app/src/main/res/layout/item_product_name_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature🔨

#118 Feature/104 seller mypage feed UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreMainFragment.kt
  app/src/main/res/layout/activity_seller_product_add_and_edit.xml
  app/src/main/res/layout/fragment_seller_store_main.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#120 Feature/114 store profile server
  app/src/main/java/com/codepatissier/keki/src/main/auth/profilesetting/SellerProfileSettingActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/ConsumerSearchActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/model/MyPageResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/model/SellerMyPageResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/model/SellerProfileEditBody.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/model/SellerProfileEditResponse.kt
  app/src/main/java/com/codepatissier/keki/src/splash/SplashActivity.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/LogoutDialog.kt
  app/src/main/java/com/codepatissier/keki/util/dialog/WithdrawalDialog.kt
  app/src/main/res/layout/activity_consumer_search.xml
  app/src/main/res/layout/activity_seller_profile_edit.xml
  app/src/main/res/layout/activity_seller_profile_setting.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/spinner_array.xml
Labels: feature🔨

#124 Feature/115 get one feed
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/model/HomePostRe.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailImageAdapter.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/model/ConsumerOneFeedDetailResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/model/Result.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/home/HomeStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/home/HomeStoreData.kt
  app/src/main/res/layout/activity_consumer_one_feed_detail.xml
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/fragment_consumer_one_feed_slide_image.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#125 Feature/103 seller add feed UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/storefeed/SellerStoreFeedAddActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeedadd/FeedImageAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeedadd/ProductNameAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeedadd/ProductNameData.kt
  app/src/main/res/layout/activity_seller_store_feed_add.xml
  app/src/main/res/layout/item_product_name_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#128 Chore/126 storeidx link
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/model/Result.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/model/Feeds.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreFeedDetailRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreFeedDetailService.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainStoreAdapter.kt
Labels: chore

#130 Feature/113 seller store feed server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/model/MyPageResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerProductFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreFeedFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/SellerStoreMainFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddService.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/SellerProductAddView.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/model/SellerProductAddBody.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/product/model/SellerProductAddResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/store/productfeed/SellerProductAdd.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/home/HomeStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchListAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchRecentPostAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchResultFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainDialog.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/consumer/ConsumerStoreMainStoreAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainDialog.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainProductAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/viewpager/storemain/seller/SellerStoreMainStoreAdapter.kt
  app/src/main/res/layout/activity_consumer_store_main.xml
  app/src/main/res/layout/activity_seller_product_add_and_edit.xml
  app/src/main/res/layout/fragment_seller_store_main.xml
  app/src/main/res/values/dimens.xml
Labels: feature🔨

#132 Feature/121 like UI
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeFragment.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/like/LikeFeedAdapter.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/like/LikeFeedData.kt
  app/src/main/res/layout/fragment_consumer_like.xml
  app/src/main/res/layout/item_like_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#127 Create README.md
  README.md
Labels: question

#136 Chore/123 search add
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/ConsumerSearchFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/RecentSeenFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/ConsumerSearchActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/model/SearchResult.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/search/SearchPopularAdapter.kt
  app/src/main/res/drawable/bg_rectangle_radius_13.xml
  app/src/main/res/layout/item_search_popular_recycler.xml
Labels: feature🔨, chore

#139 Feature/135 seller profile and product add keyboard
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditActivity.kt
  app/src/main/res/layout/activity_seller_product_add_and_edit.xml
  app/src/main/res/layout/activity_seller_profile_edit.xml
  app/src/main/res/layout/activity_seller_profile_setting.xml
Labels: feature🔨

#145 chore: 가게 피드 스크롤 수정
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/ConsumerStoreDetailFeedActivity.kt
Labels: bug, chore

#143 Chore/140 design qa oki
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/onefeed/ConsumerOneFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/ConsumerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/mypage/profileEdit/ConsumerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/RecentSeenFeedActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/ConsumerStoreMainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/store/storefeed/StoreFeedSlideImageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/SellerMyPageFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/seller/mypage/profileEdit/SellerProfileEditActivity.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/layout/activity_consumer_one_feed_detail.xml
  app/src/main/res/layout/activity_consumer_profile_edit.xml
  app/src/main/res/layout/activity_recent_seen_feed.xml
  app/src/main/res/layout/activity_seller_product_add_and_edit.xml
  app/src/main/res/layout/fragment_consumer_one_feed_slide_image.xml
  app/src/main/res/layout/fragment_non_consumer_my_page.xml
  app/src/main/res/layout/fragment_seller_my_page.xml
  app/src/main/res/layout/fragment_seller_store_main.xml
  app/src/main/res/layout/fragment_store_feed_slide_image.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#147 Feature/131 calendar modify server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendardetail/ConsumerCalendarDetailActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/ConsumerCalendarModifyView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/model/ConsumerCalendarModifyViewResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/model/ResultCalendarModifyView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/calendarmodify/model/UpdateCalendarRequest.kt
  app/src/main/res/layout/activity_consumer_calendar_add.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#141 Chore/138 design qa olivia
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/ConsumerHomeFragment.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/storefeed/StoreFeedAdapter.kt
  app/src/main/res/layout/fragment_consumer_home.xml
  app/src/main/res/layout/item_home_store_recycler.xml
  app/src/main/res/layout/item_store_feed_recycler.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: chore

#150 Chore/149 design update
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/home/ConsumerHomeFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/search/searchresult/SearchResultService.kt
  app/src/main/res/drawable-hdpi/ic_seller_home.png
  app/src/main/res/drawable-mdpi/ic_seller_home.png
  app/src/main/res/drawable-xhdpi/ic_seller_home.png
  app/src/main/res/drawable-xxhdpi/ic_seller_home.png
  app/src/main/res/drawable-xxxhdpi/ic_seller_home.png
  app/src/main/res/layout/dialog_store_main.xml
  app/src/main/res/layout/fragment_consumer_search.xml
  app/src/main/res/layout/item_search_popular_recycler.xml
  app/src/main/res/layout/item_search_recent_recycler.xml
  app/src/main/res/menu/menu_seller_main_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: chore

#151 Feature/121 like UI
  app/src/main/java/com/codepatissier/keki/src/MainActivity.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/calendar/NonConsumerCalendarFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeFragment.kt
  app/src/main/java/com/codepatissier/keki/util/NonConsumerFragment.kt
  app/src/main/java/com/codepatissier/keki/util/recycler/RecyclerViewEmptySupport.kt
  app/src/main/res/drawable-hdpi/img_cake_with_fallen_cherry.png
  app/src/main/res/drawable-mdpi/img_cake_with_fallen_cherry.png
  app/src/main/res/drawable-xhdpi/img_cake_with_fallen_cherry.png
  app/src/main/res/drawable-xxhdpi/img_cake_with_fallen_cherry.png
  app/src/main/res/drawable-xxxhdpi/img_cake_with_fallen_cherry.png
  app/src/main/res/layout/fragment_consumer_like.xml
  app/src/main/res/layout/fragment_non_consumer.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature🔨

#153 feat : 좋아요 api 연동
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeFragment.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeRetrofitInterface.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeService.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/ConsumerLikeView.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/model/ConsumerLikeFeeds.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/model/ConsumerLikeResponse.kt
  app/src/main/java/com/codepatissier/keki/src/main/consumer/like/model/ConsumerLikeResult.kt
  app/src/main/res/layout/fragment_consumer_like.xml
Labels: feature🔨

#154 Fix/148 qa bottomnavi warning
  app/src/main/java/com/codepatissier/keki/config/ApplicationClass.kt
  app/src/main/java/com/codepatissier/keki/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/codepatissier/keki/src/MainActivity.kt
Labels: bug, chore
